//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProyectoFinal.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppProyectoFinal.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acercar.
        /// </summary>
        internal static string btAcercar {
            get {
                return ResourceManager.GetString("btAcercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string btActualizar {
            get {
                return ResourceManager.GetString("btActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir favorito.
        /// </summary>
        internal static string btAddFav {
            get {
                return ResourceManager.GetString("btAddFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo libro.
        /// </summary>
        internal static string btAddNewBook {
            get {
                return ResourceManager.GetString("btAddNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alejar.
        /// </summary>
        internal static string btAlejar {
            get {
                return ResourceManager.GetString("btAlejar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btCancelar {
            get {
                return ResourceManager.GetString("btCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string btEnviar {
            get {
                return ResourceManager.GetString("btEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer.
        /// </summary>
        internal static string btLeer {
            get {
                return ResourceManager.GetString("btLeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string btLogin {
            get {
                return ResourceManager.GetString("btLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar sin iniciar sesión.
        /// </summary>
        internal static string btNoLogin {
            get {
                return ResourceManager.GetString("btNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string btOlvidaCon {
            get {
                return ResourceManager.GetString("btOlvidaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar Contraseña.
        /// </summary>
        internal static string btRecCon {
            get {
                return ResourceManager.GetString("btRecCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        internal static string btRegistrarse {
            get {
                return ResourceManager.GetString("btRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string btSubir {
            get {
                return ResourceManager.GetString("btSubir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string busqueda {
            get {
                return ResourceManager.GetString("busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué acción quiere realizar sobre el libro: .
        /// </summary>
        internal static string expActionBook {
            get {
                return ResourceManager.GetString("expActionBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiere dar el rango de autor al usuario?.
        /// </summary>
        internal static string expChangeRol {
            get {
                return ResourceManager.GetString("expChangeRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiere dar el rango de autor al usuario: .
        /// </summary>
        internal static string expChangeRol2 {
            get {
                return ResourceManager.GetString("expChangeRol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu correo registrado para recibir instrucciones para resetear tu contraseña.
        /// </summary>
        internal static string expOlvidaCon {
            get {
                return ResourceManager.GetString("expOlvidaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres enviar las instrucciones de verificación a tu correo?.
        /// </summary>
        internal static string expVerificar {
            get {
                return ResourceManager.GetString("expVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Inicio.
        /// </summary>
        internal static string help1 {
            get {
                return ResourceManager.GetString("help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su contenido varía dependiendo de si el usuario esta logado o no:.
        /// </summary>
        internal static string help10 {
            get {
                return ResourceManager.GetString("help10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para usuarios no logados, la pantalla principal muestra una lista de obras públicas y la opción de cargar un archivo propio a través de un botón en la parte inferior..
        /// </summary>
        internal static string help11 {
            get {
                return ResourceManager.GetString("help11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para usuarios logados acceden a una vista personalizada donde se presentan libros clasificados en diferentes categorías (Novedades, Más vistos y Obras públicas). En la cabecera superior se muestra información de la cuenta, con un ícono de perfil para acceder a los ajustes y otro para cerrar sesión. Además, se incluye un enlace adicional a esta página de ayuda en la cabecera. Los usuarios pueden acceder a una colección de obras de dominio público en formato EPUB. Cuenta con una barra de navegación y botones  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help12 {
            get {
                return ResourceManager.GetString("help12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Principal: Novedades.
        /// </summary>
        internal static string help13 {
            get {
                return ResourceManager.GetString("help13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se listan los últimos libros publicados por la comunidad los cuales se pueden visualizar sus detalles al pulsar sobre ellos. Cuenta con la misma navgación y funcionalidades comentadas en Obras públicas..
        /// </summary>
        internal static string help14 {
            get {
                return ResourceManager.GetString("help14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Principal: Más vistos.
        /// </summary>
        internal static string help15 {
            get {
                return ResourceManager.GetString("help15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se listan los libros más populares de la comunidad los cuales se pueden visualizar sus detalles al pulsar sobre ellos. Cuenta con la misma navgación y funcionalidades comentadas en Obras públicas..
        /// </summary>
        internal static string help16 {
            get {
                return ResourceManager.GetString("help16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Subida de libro.
        /// </summary>
        internal static string help17 {
            get {
                return ResourceManager.GetString("help17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva pantalla accesible desde el botón de la página principal de subir libro, contiene un formulario para completar la información asociada al libro que se desea subir. Este formulario incluye campos como el título, una descripción y la categoría a la que pertenece. Además, se muestra un botón con forma de clip que permite seleccionar el archivo PDF desde el dispositivo del usuario. Una vez que el formulario esté completo, al pulsar el botón de subir, el libro será almacenado y quedará pendiente de revisió [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help18 {
            get {
                return ResourceManager.GetString("help18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Detalles de libro.
        /// </summary>
        internal static string help19 {
            get {
                return ResourceManager.GetString("help19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al abrir la aplicación, se muestra una pantalla inicial desde la cual puedes iniciar sesión para acceder al contenido completo o continuar sin iniciar sesión, lo que limitará el acceso a ciertos contenidos. Si ya has iniciado sesión previamente, la aplicación recuerda esta sesión, omitiendo la pantalla inicial.
        ///.
        /// </summary>
        internal static string help2 {
            get {
                return ResourceManager.GetString("help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si se selecciona un libro de cualquier listado, se redirige a la pantalla de detalles del libro. En esta sección se presenta información relevante sobre el libro, como el título, descripción, categoría, fecha de creación, número de visualizaciones y una lista de comentarios realizados por otros usuarios. Desde esta página, los usuarios pueden interactuar de diferentes maneras: añadir un comentario pulsando el botón negro con el icono de comentario, eliminar un comentario propio, añadir o eliminar el libro d [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help20 {
            get {
                return ResourceManager.GetString("help20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si pulsas sobre el botón de comentarios, aparecerá un modal en el que podrá introducir el texto deseado. Al confirmar, el comentario se añadirá a la lista de comentarios..
        /// </summary>
        internal static string help21 {
            get {
                return ResourceManager.GetString("help21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para eliminar un comentario, se debe pulsar sobre él y se abrirá un modal de confirmación donde se solicitará verificar la acción. .
        /// </summary>
        internal static string help22 {
            get {
                return ResourceManager.GetString("help22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Lectura.
        /// </summary>
        internal static string help23 {
            get {
                return ResourceManager.GetString("help23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se muestra el contenido del libro en la parte central de la pantalla y se puede acercar o alejar el zoom mediante los botones ubicados en la parte superior. .
        /// </summary>
        internal static string help24 {
            get {
                return ResourceManager.GetString("help24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Perfil.
        /// </summary>
        internal static string help25 {
            get {
                return ResourceManager.GetString("help25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesible haciendo click en el icono de usuario de la cabecera. Aquí se muestra información personal del usuario, como su imagen de perfil, nombre, correo electrónico y fecha de creación de la cuenta. Además, se incluye una lista de libros marcados como favoritos, desde donde se puede acceder a sus detalles. Desde esta pantalla, el usuario también puede acceder a los ajustes del perfil pulsando el icono en la esquina superior derecha o solicitar un cambio de rol de usuario básico a autor pulsando sobre el e [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help26 {
            get {
                return ResourceManager.GetString("help26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si un usuario básico selecciona el estado de la cuenta para cambiar a autor, se mostrará un modal de confirmación. En caso de aceptar, la solicitud quedará pendiente de revisión por parte de un administrador. Los usuarios que ya sean autores o que estén en proceso de verificación recibirán un mensaje explicando la razón por la cual no es posible realizar esta acción (Ejemplo: si eres autor dice que no puedes modificar el rol ya que ya eres un autor). .
        /// </summary>
        internal static string help27 {
            get {
                return ResourceManager.GetString("help27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Ajustes de Perfil.
        /// </summary>
        internal static string help28 {
            get {
                return ResourceManager.GetString("help28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde esta pantalla los usuarios pueden modificar ciertas configuraciones. Estas opciones son cambiar el nombre, la imagen de perfil o configuraciones para cambiar el tema de la aplicación (claro u oscuro), el tamaño de fuente (pequeña, mediana o grande) y el idioma (español o inglés). Los cambios realizados pueden visualizarse en tiempo real, pero para aplicarlos definitivamente es necesario pulsar el botón de Actualizar..
        /// </summary>
        internal static string help29 {
            get {
                return ResourceManager.GetString("help29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Login.
        /// </summary>
        internal static string help3 {
            get {
                return ResourceManager.GetString("help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Categorías.
        /// </summary>
        internal static string help30 {
            get {
                return ResourceManager.GetString("help30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la pantalla de categorías, los administradores pueden visualizar todas las categorías disponibles en la plataforma. Cada categoría se muestra con un icono de papelera asociado, que permite eliminarla con un solo clic. Además, se ofrece un botón destacado para añadir una nueva categoría, el cual abre un formulario sencillo donde se introduce el nombre de la categoría a crear. Para facilitar la navegación entre las distintas páginas del panel de administración, la interfaz incluye una barra de navegación u [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help31 {
            get {
                return ResourceManager.GetString("help31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el caso de pulsar el icono de la papelera de una categoría se nos muestra un modal de confirmación para asegurar que se desea eliminar dicha categoría. Este modal pregunta al usuario si realmente desea eliminar la categoría seleccionada, con opciones para Confirmar o Cancelar la acción. .
        /// </summary>
        internal static string help32 {
            get {
                return ResourceManager.GetString("help32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el caso de pulsar el botón de añadir una nueva categoría se nos muestra un modal para introducir el nombre de la nueva categoría. .
        /// </summary>
        internal static string help33 {
            get {
                return ResourceManager.GetString("help33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Libros.
        /// </summary>
        internal static string help34 {
            get {
                return ResourceManager.GetString("help34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la pantalla de libros, los administradores pueden visualizar la lista completa de libros que han sido subidos por la comunidad. Al pulsar sobre cualquiera de estos libros, se puede acceder a la vista de detalles, como lo haría un usuario común. Además, los administradores tienen la opción de subir nuevos archivos PDF, utilizando un botón con el respectivo icono, de la misma forma que un autor. Otra funcionalidad importante es la opción de filtrar los libros activando un toggle, lo que permite mostrar úni [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help35 {
            get {
                return ResourceManager.GetString("help35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al pulsar el icono de los tres puntos, se despliega un modal con diversas opciones disponibles para el libro seleccionado. Las opciones incluyen: .
        /// </summary>
        internal static string help36 {
            get {
                return ResourceManager.GetString("help36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir: Esta opción solo está disponible para libros que han sido cargados, pero aún están pendientes de aprobación por parte de un autor. Al seleccionar esta opción, el libro se publica y se hace visible para todos los usuarios de la plataforma. .
        /// </summary>
        internal static string help37 {
            get {
                return ResourceManager.GetString("help37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar: Al seleccionar esta opción, el administrador es redirigido a una pantalla específica para editar los detalles del libro seleccionado. Esto permite modificar información como el título, la descripción, el autor, entre otros. .
        /// </summary>
        internal static string help38 {
            get {
                return ResourceManager.GetString("help38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar: Esta opción permite eliminar el libro de manera definitiva. Al seleccionar Borrar, el administrador recibe una confirmación antes de proceder con la eliminación para evitar errores. .
        /// </summary>
        internal static string help39 {
            get {
                return ResourceManager.GetString("help39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se muestra un formulario con dos campos: correo electrónico y contraseña. La contraseña cuenta con un ícono que permite alternar entre mostrarla en texto claro u ocultarla. En esta vista, tieneS tres opciones: iniciar sesión introduciendo correctamente los datos, acceder a la pantalla de recuperación de contraseña (clicando en &apos;¿Has olvidado la contraseña?&apos;) o crear una cuenta nueva pulsando en el texto correspondiente..
        /// </summary>
        internal static string help4 {
            get {
                return ResourceManager.GetString("help4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al seleccionar la opción de editar, se accede a una pantalla que presenta un formulario prellenado con los datos del libro que se desea modificar. En este formulario, se podrán actualizar los campos más relevantes, como el título, la descripción y la categoría del libro. Esta funcionalidad permite a los administradores realizar ajustes rápidos y precisos a la información de los libros de la plataforma. .
        /// </summary>
        internal static string help40 {
            get {
                return ResourceManager.GetString("help40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Subida de libro.
        /// </summary>
        internal static string help41 {
            get {
                return ResourceManager.GetString("help41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva pantalla accesible desde el botón de la página principal de subir libro, contiene un formulario para completar la información asociada al libro que se desea subir. Este formulario incluye campos como el título, una descripción y la categoría a la que pertenece. Además, se muestra un botón con forma de clip que permite seleccionar el archivo PDF desde el dispositivo del usuario. Una vez que el formulario esté completo, al pulsar el botón de subir, el libro será almacenado y quedará pendiente de revisió [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help42 {
            get {
                return ResourceManager.GetString("help42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Detalles de libro.
        /// </summary>
        internal static string help43 {
            get {
                return ResourceManager.GetString("help43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si se selecciona un libro, se redirige a la pantalla de detalles del libro. En esta sección se presenta información relevante sobre el libro, como el título, descripción, categoría, fecha de creación, número de visualizaciones y una lista de comentarios realizados por otros usuarios. Desde esta página, los usuarios pueden interactuar de diferentes maneras: añadir un comentario pulsando el botón negro con el icono de comentario, eliminar un comentario, añadir o eliminar el libro de su lista de favoritos medi [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help44 {
            get {
                return ResourceManager.GetString("help44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si pulsas sobre el botón de comentarios, aparecerá un modal en el que podrá introducir el texto deseado. Al confirmar, el comentario se añadirá a la lista de comentarios..
        /// </summary>
        internal static string help45 {
            get {
                return ResourceManager.GetString("help45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para eliminar un comentario, se debe pulsar sobre él y se abrirá un modal de confirmación donde se solicitará verificar la acción. .
        /// </summary>
        internal static string help46 {
            get {
                return ResourceManager.GetString("help46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Usuarios.
        /// </summary>
        internal static string help47 {
            get {
                return ResourceManager.GetString("help47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la pantalla de usuarios, se muestra una lista de los usuarios registrados en la aplicación, excluyendo aquellos con el rol de administrador, ya que la gestión de este tipo de usuarios se realiza directamente en Firebase, donde se asignan y eliminan los roles. Desde esta pantalla, es posible eliminar usuarios simplemente pulsando el icono de la papelera asociado a cada uno. Además, se puede filtrar la lista activando un toggle que permite mostrar solo aquellos usuarios que han solicitado ser autores y est [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help48 {
            get {
                return ResourceManager.GetString("help48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el caso de pulsar el icono de tres puntos asociado a usuarios pendientes, se mostrará un modal que permite al administrador aceptar o denegar el cambio de rol de dicho usuario a autor. Si se opta por denegar la solicitud, el rol del usuario volverá a ser el de usuario estándar, y este podrá solicitar nuevamente convertirse en autor en el futuro si así lo desea. .
        /// </summary>
        internal static string help49 {
            get {
                return ResourceManager.GetString("help49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Recuperar Contaseña.
        /// </summary>
        internal static string help5 {
            get {
                return ResourceManager.GetString("help5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Perfil.
        /// </summary>
        internal static string help50 {
            get {
                return ResourceManager.GetString("help50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesible haciendo click en el icono de usuario de la cabecera. Aquí se muestra información personal del usuario, como su imagen de perfil, nombre, correo electrónico y fecha de creación de la cuenta. Además, se incluye una lista de libros marcados como favoritos, desde donde se puede acceder a sus detalles. Desde esta pantalla, el usuario también puede acceder a los ajustes del perfil pulsando el icono en la esquina superior derecha..
        /// </summary>
        internal static string help51 {
            get {
                return ResourceManager.GetString("help51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se muestra un campo donde puedes introducir el correo asociado a la cuenta. Tras enviar el formulario, la aplicación envía un correo con las instrucciones para restablecer la contraseña..
        /// </summary>
        internal static string help6 {
            get {
                return ResourceManager.GetString("help6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Registro .
        /// </summary>
        internal static string help7 {
            get {
                return ResourceManager.GetString("help7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se muestra un formulario que solicita información como nombre, correo válido, contraseña (de al menos seis caracteres) y confirmación de esta. Si no existe una cuenta asociada al correo ingresado, se completa el registro y se redirige al usuario a la pantalla de inicio de sesión para acceder con las nuevas credenciales..
        /// </summary>
        internal static string help8 {
            get {
                return ResourceManager.GetString("help8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Principal: Obras Públicas.
        /// </summary>
        internal static string help9 {
            get {
                return ResourceManager.GetString("help9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadiendo comentario.
        /// </summary>
        internal static string msnAddComment {
            get {
                return ResourceManager.GetString("msnAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadido a favoritos.
        /// </summary>
        internal static string msnAddedFav {
            get {
                return ResourceManager.GetString("msnAddedFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que desea eliminar el libro.
        /// </summary>
        internal static string msnAskDelBook {
            get {
                return ResourceManager.GetString("msnAskDelBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que desea eliminar la categoría .
        /// </summary>
        internal static string msnAskDelete {
            get {
                return ResourceManager.GetString("msnAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de querer verificar tu usuario .
        /// </summary>
        internal static string msnAskVerify {
            get {
                return ResourceManager.GetString("msnAskVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al comprobar si es favorito: .
        /// </summary>
        internal static string msnCheckFav {
            get {
                return ResourceManager.GetString("msnCheckFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string msnCheckPassword {
            get {
                return ResourceManager.GetString("msnCheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando usuario....
        /// </summary>
        internal static string msnCheckUser {
            get {
                return ResourceManager.GetString("msnCheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario añadido.
        /// </summary>
        internal static string msnComentAdded {
            get {
                return ResourceManager.GetString("msnComentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario eliminado.
        /// </summary>
        internal static string msnComentDeleted {
            get {
                return ResourceManager.GetString("msnComentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas eliminar este mensaje?.
        /// </summary>
        internal static string msnConfirmDelComment {
            get {
                return ResourceManager.GetString("msnConfirmDelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu contraseña.
        /// </summary>
        internal static string msnCPassword {
            get {
                return ResourceManager.GetString("msnCPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creando cuenta....
        /// </summary>
        internal static string msnCreateUser {
            get {
                return ResourceManager.GetString("msnCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrando registro provisional....
        /// </summary>
        internal static string msnDelAux {
            get {
                return ResourceManager.GetString("msnDelAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Libro.
        /// </summary>
        internal static string msnDelBook {
            get {
                return ResourceManager.GetString("msnDelBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar comentario.
        /// </summary>
        internal static string msnDelComment {
            get {
                return ResourceManager.GetString("msnDelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Categoría.
        /// </summary>
        internal static string msnDeleteCategory {
            get {
                return ResourceManager.GetString("msnDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado de favoritos.
        /// </summary>
        internal static string msnDeletedFav {
            get {
                return ResourceManager.GetString("msnDeletedFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando libro....
        /// </summary>
        internal static string msnDeletingBook {
            get {
                return ResourceManager.GetString("msnDeletingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando categoría....
        /// </summary>
        internal static string msnDeletingCat {
            get {
                return ResourceManager.GetString("msnDeletingCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un email válido.
        /// </summary>
        internal static string msnEmail {
            get {
                return ResourceManager.GetString("msnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el libro: .
        /// </summary>
        internal static string msnErrorBook {
            get {
                return ResourceManager.GetString("msnErrorBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al crear la cuenta: .
        /// </summary>
        internal static string msnErrorCreateUser {
            get {
                return ResourceManager.GetString("msnErrorCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer credenciales: .
        /// </summary>
        internal static string msnErrorCreden {
            get {
                return ResourceManager.GetString("msnErrorCreden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo seleccionar la imagen..
        /// </summary>
        internal static string msnErrorImage {
            get {
                return ResourceManager.GetString("msnErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la información del usuario: .
        /// </summary>
        internal static string msnErrorLoadUser {
            get {
                return ResourceManager.GetString("msnErrorLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al solicitar la petición: .
        /// </summary>
        internal static string msnErrorRequest {
            get {
                return ResourceManager.GetString("msnErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al añadir a favoritos: .
        /// </summary>
        internal static string msnFailAddedFav {
            get {
                return ResourceManager.GetString("msnFailAddedFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al añadir el comentario: .
        /// </summary>
        internal static string msnFailComment {
            get {
                return ResourceManager.GetString("msnFailComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al eliminar el comentario: .
        /// </summary>
        internal static string msnFailDelComent {
            get {
                return ResourceManager.GetString("msnFailDelComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al eliminar de favoritos: .
        /// </summary>
        internal static string msnFailDeletedFav {
            get {
                return ResourceManager.GetString("msnFailDeletedFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al iniciar sesión: .
        /// </summary>
        internal static string msnFailLog {
            get {
                return ResourceManager.GetString("msnFailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al guardar al usuario: .
        /// </summary>
        internal static string msnFailSaveUser {
            get {
                return ResourceManager.GetString("msnFailSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al actualizar el perfil: .
        /// </summary>
        internal static string msnFailUpdatePerfil {
            get {
                return ResourceManager.GetString("msnFailUpdatePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al actualizar la imagen:.
        /// </summary>
        internal static string msnFailUploadImage {
            get {
                return ResourceManager.GetString("msnFailUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al comprobar el usuario: .
        /// </summary>
        internal static string msnFailUser {
            get {
                return ResourceManager.GetString("msnFailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizará tu cuenta a una de escritor tras ser procesada tu solicitud..
        /// </summary>
        internal static string msnInfoVerify {
            get {
                return ResourceManager.GetString("msnInfoVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando sesión....
        /// </summary>
        internal static string msnLogin {
            get {
                return ResourceManager.GetString("msnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu nombre.
        /// </summary>
        internal static string msnName {
            get {
                return ResourceManager.GetString("msnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Categoría.
        /// </summary>
        internal static string msnNewCategory {
            get {
                return ResourceManager.GetString("msnNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Comentario.
        /// </summary>
        internal static string msnNewComment {
            get {
                return ResourceManager.GetString("msnNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        internal static string msnNoUserFound {
            get {
                return ResourceManager.GetString("msnNoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu contraseña (6 caracteres mínimo).
        /// </summary>
        internal static string msnPassword {
            get {
                return ResourceManager.GetString("msnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación pendiente de ser aprobada.
        /// </summary>
        internal static string msnPendingVerified {
            get {
                return ResourceManager.GetString("msnPendingVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardando la información del usuario....
        /// </summary>
        internal static string msnSaveUser {
            get {
                return ResourceManager.GetString("msnSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo enviado a: .
        /// </summary>
        internal static string msnSendedEmail {
            get {
                return ResourceManager.GetString("msnSendedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviando correo a .
        /// </summary>
        internal static string msnSendEmail {
            get {
                return ResourceManager.GetString("msnSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al enviar el correo a .
        /// </summary>
        internal static string msnSendFail {
            get {
                return ResourceManager.GetString("msnSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud creada con éxito.
        /// </summary>
        internal static string msnSuccesRequest {
            get {
                return ResourceManager.GetString("msnSuccesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado con éxito.
        /// </summary>
        internal static string msnSuccessUploadPerfil {
            get {
                return ResourceManager.GetString("msnSuccessUploadPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario creado con éxito.
        /// </summary>
        internal static string msnSuccesUser {
            get {
                return ResourceManager.GetString("msnSuccesUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando perfil....
        /// </summary>
        internal static string msnUpdatePerfil {
            get {
                return ResourceManager.GetString("msnUpdatePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo imagen....
        /// </summary>
        internal static string msnUploadImage {
            get {
                return ResourceManager.GetString("msnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estas verificado.
        /// </summary>
        internal static string msnVerified {
            get {
                return ResourceManager.GetString("msnVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No verificado.
        /// </summary>
        internal static string noVerificado {
            get {
                return ResourceManager.GetString("noVerificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        internal static string opAdmin {
            get {
                return ResourceManager.GetString("opAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        internal static string opBiblioteca {
            get {
                return ResourceManager.GetString("opBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string opConfig {
            get {
                return ResourceManager.GetString("opConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string opInicio {
            get {
                return ResourceManager.GetString("opInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer libro.
        /// </summary>
        internal static string opLeer {
            get {
                return ResourceManager.GetString("opLeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del libro.
        /// </summary>
        internal static string opLibro {
            get {
                return ResourceManager.GetString("opLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil de usuario.
        /// </summary>
        internal static string opPerfil {
            get {
                return ResourceManager.GetString("opPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ej: Ciencia Ficción.
        /// </summary>
        internal static string phCategory {
            get {
                return ResourceManager.GetString("phCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu comentario....
        /// </summary>
        internal static string phComent {
            get {
                return ResourceManager.GetString("phComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string phCon {
            get {
                return ResourceManager.GetString("phCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string phCorreo {
            get {
                return ResourceManager.GetString("phCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del libro.
        /// </summary>
        internal static string phDescripcion {
            get {
                return ResourceManager.GetString("phDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string phEmail {
            get {
                return ResourceManager.GetString("phEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de recuperación.
        /// </summary>
        internal static string phEmailrecover {
            get {
                return ResourceManager.GetString("phEmailrecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la contraseña.
        /// </summary>
        internal static string phPassword {
            get {
                return ResourceManager.GetString("phPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repite la contraseña.
        /// </summary>
        internal static string phRepCon {
            get {
                return ResourceManager.GetString("phRepCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título del libro.
        /// </summary>
        internal static string phTitulo {
            get {
                return ResourceManager.GetString("phTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string phUsuario {
            get {
                return ResourceManager.GetString("phUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Categoría....
        /// </summary>
        internal static string searchCategory {
            get {
                return ResourceManager.GetString("searchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Nombre....
        /// </summary>
        internal static string searchName {
            get {
                return ResourceManager.GetString("searchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar título....
        /// </summary>
        internal static string searchTitle {
            get {
                return ResourceManager.GetString("searchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string txtAceptar {
            get {
                return ResourceManager.GetString("txtAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir categoría.
        /// </summary>
        internal static string txtAddCategoria {
            get {
                return ResourceManager.GetString("txtAddCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Comentario.
        /// </summary>
        internal static string txtAddComment {
            get {
                return ResourceManager.GetString("txtAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, rellene todos los datos a continuación para solicitar la publicación de su libro.
        /// </summary>
        internal static string txtAddNewBook {
            get {
                return ResourceManager.GetString("txtAddNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador:.
        /// </summary>
        internal static string txtAdministrador {
            get {
                return ResourceManager.GetString("txtAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        internal static string txtAjustes {
            get {
                return ResourceManager.GetString("txtAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes de usuario.
        /// </summary>
        internal static string txtAjustes2 {
            get {
                return ResourceManager.GetString("txtAjustes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría ya existe.
        /// </summary>
        internal static string txtAlreadyCat {
            get {
                return ResourceManager.GetString("txtAlreadyCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una categoría.
        /// </summary>
        internal static string txtAskCat {
            get {
                return ResourceManager.GetString("txtAskCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que desea eliminar al usuario: .
        /// </summary>
        internal static string txtAskDeleteUser {
            get {
                return ResourceManager.GetString("txtAskDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce la descripción.
        /// </summary>
        internal static string txtAskDesc {
            get {
                return ResourceManager.GetString("txtAskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un PDF.
        /// </summary>
        internal static string txtAskpdf {
            get {
                return ResourceManager.GetString("txtAskpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el título.
        /// </summary>
        internal static string txtAskTitulo {
            get {
                return ResourceManager.GetString("txtAskTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor: .
        /// </summary>
        internal static string txtAutor {
            get {
                return ResourceManager.GetString("txtAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string txtAyuda {
            get {
                return ResourceManager.GetString("txtAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Besoculto.
        /// </summary>
        internal static string txtBienvenida {
            get {
                return ResourceManager.GetString("txtBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string txtBorrar {
            get {
                return ResourceManager.GetString("txtBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría: .
        /// </summary>
        internal static string txtCategoria {
            get {
                return ResourceManager.GetString("txtCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        internal static string txtCategorias {
            get {
                return ResourceManager.GetString("txtCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría del libro.
        /// </summary>
        internal static string txtCategoryBook {
            get {
                return ResourceManager.GetString("txtCategoryBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría creada correctamente.
        /// </summary>
        internal static string txtCatOk {
            get {
                return ResourceManager.GetString("txtCatOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claro.
        /// </summary>
        internal static string txtClaro {
            get {
                return ResourceManager.GetString("txtClaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un comentario:.
        /// </summary>
        internal static string txtComent {
            get {
                return ResourceManager.GetString("txtComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string txtComentario {
            get {
                return ResourceManager.GetString("txtComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string txtConfirmar {
            get {
                return ResourceManager.GetString("txtConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        internal static string txtCuenta {
            get {
                return ResourceManager.GetString("txtCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Usuario.
        /// </summary>
        internal static string txtDeleteUser {
            get {
                return ResourceManager.GetString("txtDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando usuario....
        /// </summary>
        internal static string txtDeletingUser {
            get {
                return ResourceManager.GetString("txtDeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        internal static string txtDenegar {
            get {
                return ResourceManager.GetString("txtDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string txtEditar {
            get {
                return ResourceManager.GetString("txtEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar información del libro.
        /// </summary>
        internal static string txtEditBook {
            get {
                return ResourceManager.GetString("txtEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editorial: .
        /// </summary>
        internal static string txtEditorial {
            get {
                return ResourceManager.GetString("txtEditorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string txtEliminar {
            get {
                return ResourceManager.GetString("txtEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el nombre de la categoría:.
        /// </summary>
        internal static string txtEnterCat {
            get {
                return ResourceManager.GetString("txtEnterCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer el PDF: .
        /// </summary>
        internal static string txtErrorPdf {
            get {
                return ResourceManager.GetString("txtErrorPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string txtEspanol {
            get {
                return ResourceManager.GetString("txtEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la cuenta.
        /// </summary>
        internal static string txtEstadoCuenta {
            get {
                return ResourceManager.GetString("txtEstadoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo crear la categoría: .
        /// </summary>
        internal static string txtFailCat {
            get {
                return ResourceManager.GetString("txtFailCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al actualizar la información del documento: .
        /// </summary>
        internal static string txtFailUpdateInfo {
            get {
                return ResourceManager.GetString("txtFailUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al subir el documento.
        /// </summary>
        internal static string txtFailUpload {
            get {
                return ResourceManager.GetString("txtFailUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al subir la información del documento: .
        /// </summary>
        internal static string txtFailUploadInfo {
            get {
                return ResourceManager.GetString("txtFailUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorito.
        /// </summary>
        internal static string txtFav {
            get {
                return ResourceManager.GetString("txtFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir a favoritos.
        /// </summary>
        internal static string txtFavAdd {
            get {
                return ResourceManager.GetString("txtFavAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar de favoritos.
        /// </summary>
        internal static string txtFavDel {
            get {
                return ResourceManager.GetString("txtFavDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string txtFecha {
            get {
                return ResourceManager.GetString("txtFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por pendientes.
        /// </summary>
        internal static string txtFilterpending {
            get {
                return ResourceManager.GetString("txtFilterpending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de fuente.
        /// </summary>
        internal static string txtFontsize {
            get {
                return ResourceManager.GetString("txtFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grande.
        /// </summary>
        internal static string txtGrande {
            get {
                return ResourceManager.GetString("txtGrande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string txtIdioma {
            get {
                return ResourceManager.GetString("txtIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string txtIngles {
            get {
                return ResourceManager.GetString("txtIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN: .
        /// </summary>
        internal static string txtISBN {
            get {
                return ResourceManager.GetString("txtISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectura.
        /// </summary>
        internal static string txtLectura {
            get {
                return ResourceManager.GetString("txtLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string txtLibros {
            get {
                return ResourceManager.GetString("txtLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros favoritos.
        /// </summary>
        internal static string txtLibrosFav {
            get {
                return ResourceManager.GetString("txtLibrosFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando más libros ....
        /// </summary>
        internal static string txtLoadingBooks {
            get {
                return ResourceManager.GetString("txtLoadingBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conéctate, por favor.
        /// </summary>
        internal static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediana.
        /// </summary>
        internal static string txtMediana {
            get {
                return ResourceManager.GetString("txtMediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembro.
        /// </summary>
        internal static string txtMiembro {
            get {
                return ResourceManager.GetString("txtMiembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más vistos.
        /// </summary>
        internal static string txtMostViewed {
            get {
                return ResourceManager.GetString("txtMostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor desconocido.
        /// </summary>
        internal static string txtNoAutor {
            get {
                return ResourceManager.GetString("txtNoAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El libro no existe en la base de datos..
        /// </summary>
        internal static string txtNoBook {
            get {
                return ResourceManager.GetString("txtNoBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin categoría.
        /// </summary>
        internal static string txtNoCategoria {
            get {
                return ResourceManager.GetString("txtNoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay categorías disponibles en este momento..
        /// </summary>
        internal static string txtNoCategories {
            get {
                return ResourceManager.GetString("txtNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay Comentarios disponibles en este momento..
        /// </summary>
        internal static string txtNoComent {
            get {
                return ResourceManager.GetString("txtNoComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin descripción.
        /// </summary>
        internal static string txtNoDescripcion {
            get {
                return ResourceManager.GetString("txtNoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desconocida.
        /// </summary>
        internal static string txtNoFecha {
            get {
                return ResourceManager.GetString("txtNoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se seleccionó ningún archivo..
        /// </summary>
        internal static string txtNoFile {
            get {
                return ResourceManager.GetString("txtNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay libros disponibles en este momento..
        /// </summary>
        internal static string txtNoLibros {
            get {
                return ResourceManager.GetString("txtNoLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay libros favoritos..
        /// </summary>
        internal static string txtNoLibrosFav {
            get {
                return ResourceManager.GetString("txtNoLibrosFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estas logeado.
        /// </summary>
        internal static string txtNoLogin {
            get {
                return ResourceManager.GetString("txtNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        internal static string txtNombreUsuario {
            get {
                return ResourceManager.GetString("txtNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título desconocido.
        /// </summary>
        internal static string txtNoTitulo {
            get {
                return ResourceManager.GetString("txtNoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usario desconocido.
        /// </summary>
        internal static string txtNoUser {
            get {
                return ResourceManager.GetString("txtNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay usuarios disponibles en este momento..
        /// </summary>
        internal static string txtNoUsers {
            get {
                return ResourceManager.GetString("txtNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novedades.
        /// </summary>
        internal static string txtNovedades {
            get {
                return ResourceManager.GetString("txtNovedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string txtOlvidaCon {
            get {
                return ResourceManager.GetString("txtOlvidaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscuro.
        /// </summary>
        internal static string txtOscuro {
            get {
                return ResourceManager.GetString("txtOscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de inicio.
        /// </summary>
        internal static string txtPageInit {
            get {
                return ResourceManager.GetString("txtPageInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Páginas:.
        /// </summary>
        internal static string txtPages {
            get {
                return ResourceManager.GetString("txtPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer Pdf del dispositivo.
        /// </summary>
        internal static string txtPdfDispositivo {
            get {
                return ResourceManager.GetString("txtPdfDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pequeña.
        /// </summary>
        internal static string txtPequena {
            get {
                return ResourceManager.GetString("txtPequena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obras Públicas.
        /// </summary>
        internal static string txtPublicBooks {
            get {
                return ResourceManager.GetString("txtPublicBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una cuenta nueva.
        /// </summary>
        internal static string txtRegistrarse {
            get {
                return ResourceManager.GetString("txtRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string txtRegistro {
            get {
                return ResourceManager.GetString("txtRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión para acceder a tu perfil.
        /// </summary>
        internal static string txtRequestLog {
            get {
                return ResourceManager.GetString("txtRequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string txtSalir {
            get {
                return ResourceManager.GetString("txtSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionado el archivo: .
        /// </summary>
        internal static string txtSelected {
            get {
                return ResourceManager.GetString("txtSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis: .
        /// </summary>
        internal static string txtSinopsis {
            get {
                return ResourceManager.GetString("txtSinopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        internal static string txtSuccess {
            get {
                return ResourceManager.GetString("txtSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información subida con éxito, pendiente de aprobación por un administrador.
        /// </summary>
        internal static string txtSuccesUpload {
            get {
                return ResourceManager.GetString("txtSuccesUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada con éxito.
        /// </summary>
        internal static string txtSuccesUploadInfo {
            get {
                return ResourceManager.GetString("txtSuccesUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño: .
        /// </summary>
        internal static string txtTamano {
            get {
                return ResourceManager.GetString("txtTamano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        internal static string txtTema {
            get {
                return ResourceManager.GetString("txtTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título: .
        /// </summary>
        internal static string txtTitulo {
            get {
                return ResourceManager.GetString("txtTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol del usuario actualizado.
        /// </summary>
        internal static string txtUpdateRol {
            get {
                return ResourceManager.GetString("txtUpdateRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir libro.
        /// </summary>
        internal static string txtUploadBook {
            get {
                return ResourceManager.GetString("txtUploadBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo la información del documento... .
        /// </summary>
        internal static string txtUploadInfo {
            get {
                return ResourceManager.GetString("txtUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo el documento....
        /// </summary>
        internal static string txtUploading {
            get {
                return ResourceManager.GetString("txtUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta de Usuario.
        /// </summary>
        internal static string txtUserAccount {
            get {
                return ResourceManager.GetString("txtUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string txtUsuario {
            get {
                return ResourceManager.GetString("txtUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string txtUsuarios {
            get {
                return ResourceManager.GetString("txtUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar correo.
        /// </summary>
        internal static string txtVerificar {
            get {
                return ResourceManager.GetString("txtVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizaciones:.
        /// </summary>
        internal static string txtVisualizaciones {
            get {
                return ResourceManager.GetString("txtVisualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string txtWarning {
            get {
                return ResourceManager.GetString("txtWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificado.
        /// </summary>
        internal static string verificado {
            get {
                return ResourceManager.GetString("verificado", resourceCulture);
            }
        }
    }
}
